name: 'cortex_skills_cdc'
version: '1.0.0'

profile: 'cortex_skills_cdc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  source_database: "{{ env_var('DBT_SOURCE_DATABASE', 'PRODUCT') }}"

models:
  cortex_skills_cdc:
    staging:
      +materialized: view
      +schema: UPDATES
    silver:
      +materialized: table
      +schema: UPDATES
